[package]
name = "finchers-session"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[dependencies]
cookie = { version = "0.11.0", features = ["secure"] }
finchers = { version = "0.12.0-alpha.7", features = ["secure"] }
futures = "0.1.24"
http = "0.1.13"
serde = { version = "1.0.79", features = ["derive"] }
serde_json = "1.0.30"

[patch.crates-io.finchers]
git = "https://github.com/finchers-rs/finchers.git"
features = ["secure"]
